"""Init

Revision ID: b71ad72326d7
Revises: 
Create Date: 2022-01-27 15:49:01.855255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71ad72326d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('plot', sa.String(length=1000), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.Column('movie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre'], ['genres.id'], name='fk_movies_genres_genres_genre_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie'], ['movies.id'], name='fk_movies_genres_movies_movie_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_genres')
    op.drop_table('movies')
    op.drop_table('genres')
    # ### end Alembic commands ###
