"""Make Movie.title to be 120 of length

Revision ID: c42a5c77800a
Revises: cd052dae85f0
Create Date: 2022-01-27 15:43:50.057973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42a5c77800a'
down_revision = 'cd052dae85f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
