"""Remove MovieGenre table

Revision ID: cd052dae85f0
Revises: 65ae35150435
Create Date: 2022-01-27 11:33:29.704646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd052dae85f0'
down_revision = '65ae35150435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.Column('movie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre'], ['genres.id'], name='fk_movies_genres_genres_genre_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie'], ['movies.id'], name='fk_movies_genres_movies_movie_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movies_x_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies_x_genres',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('genre', sa.INTEGER(), nullable=True),
    sa.Column('movie', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['genre'], ['genres.id'], name='fk_movies_x_genres_genres_genre_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie'], ['movies.id'], name='fk_movies_x_genres_movies_movie_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movies_genres')
    # ### end Alembic commands ###
